#!/usr/bin/env sh
set -e

if git diff --name-only HEAD@{1} HEAD | grep --silent '^pnpm-lock.yaml'; then
  echo "📦 pnpm-lock.yaml was changed."
  echo "Running pnpm deps:reinstall to reinstall your dependencies..."
  pnpm deps:reinstall
fi
